[2025-09-02T07:39:02.663+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-02T07:39:02.726+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline_data_rekapitulasi.extract_data manual__2025-09-02T07:38:53.702175+00:00 [queued]>
[2025-09-02T07:39:02.744+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline_data_rekapitulasi.extract_data manual__2025-09-02T07:38:53.702175+00:00 [queued]>
[2025-09-02T07:39:02.746+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-09-02T07:39:02.777+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_data> on 2025-09-02 07:38:53.702175+00:00
[2025-09-02T07:39:02.806+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'pipeline_data_rekapitulasi', 'extract_data', 'manual__2025-09-02T07:38:53.702175+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_rekapitulasi.py', '--cfg-path', '/tmp/tmp7l6mhi8s']
[2025-09-02T07:39:02.803+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=488) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-09-02T07:39:02.810+0000] {standard_task_runner.py:63} INFO - Started process 497 to run task
[2025-09-02T07:39:02.810+0000] {standard_task_runner.py:91} INFO - Job 3: Subtask extract_data
[2025-09-02T07:39:02.950+0000] {task_command.py:426} INFO - Running <TaskInstance: pipeline_data_rekapitulasi.extract_data manual__2025-09-02T07:38:53.702175+00:00 [running]> on host 231ead08851d
[2025-09-02T07:39:03.174+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pipeline_data_rekapitulasi' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2025-09-02T07:38:53.702175+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-02T07:38:53.702175+00:00'
[2025-09-02T07:39:03.177+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-02T07:39:05.240+0000] {logging_mixin.py:188} INFO - File berhasil diunduh: data_raw.xlsx
[2025-09-02T07:39:05.247+0000] {python.py:237} INFO - Done. Returned value was: data_raw.xlsx
[2025-09-02T07:39:05.250+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-02T07:39:05.309+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=pipeline_data_rekapitulasi, task_id=extract_data, run_id=manual__2025-09-02T07:38:53.702175+00:00, execution_date=20250902T073853, start_date=20250902T073902, end_date=20250902T073905
[2025-09-02T07:39:05.402+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-09-02T07:39:05.451+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-09-02T07:39:05.456+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
